theme: jekyll-theme-cayman
domain: helloukraine.ch      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: http://helloukraine.ch
baseurl: /

title: Default Title
tagline: "..."

revolut: https://www.revolut.com/referral/pascal30y!MAR1-22-AR

defaults:
  - scope:
      path: ""
    values:
      layout: "default"