theme: jekyll-theme-cayman
domain: www.helloukraine.ch      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: http://www.helloukraine.ch
baseurl: /

title: Hello Ukraine
description: "..."

revolut: https://www.revolut.com/referral/pascal30y!MAR1-22-AR
contactform: https://forms.zohopublic.eu/helloukrainech/form/Contact/formperma/0BLf1QF03ZRSGTgvQgJfUay_IhGAagmouP6iTl387Vo


twitter:
  setup: https://publish.twitter.com/?buttonType=TweetButton&widget=Button
  text: https://www.HelloUkraine.ch Portal mit Tipps für Flüchtlinge aus der Ukraine zu einem gelungenen Start in der Schweiz #StandWithUkraine
  de: <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Portal mit Tipps für Flüchtlinge aus der Ukraine zu einem gelungenen Start in der Schweiz" data-url="https://www.HelloUkraine.ch" data-hashtags="StandWithUkraine" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  uk: <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Портал з порадами для біженців з України про успішний старт у Швейцарії" data-url="https://www.HelloUkraine.ch" data-hashtags="StandWithUkraine" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  ru: <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Портал с советами для беженцев из Украины об успешном старте в Швейцарии" data-url="https://www.HelloUkraine.ch" data-hashtags="StandWithUkraine" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  en: <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Portal with tips for refugees from Ukraine on a successful start in Switzerland" data-url="https://www.HelloUkraine.ch" data-hashtags="StandWithUkraine" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


plugins:
  - jemoji
  - jekyll-spaceship
  



defaults:
  - scope:
      path: ""
    values:
      layout: "default"


