theme: jekyll-theme-cayman
domain: www.helloukraine.ch      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://www.helloukraine.ch
baseurl: /

title: Hello Ukraine
description: "..."

revolut: https://www.revolut.com/referral/pascal30y!MAR1-22-AR
contactform: https://forms.zohopublic.eu/helloukrainech/form/Contact/formperma/0BLf1QF03ZRSGTgvQgJfUay_IhGAagmouP6iTl387Vo

# Social Media Share: Default Messages
# Hint: https://sharelinkgenerator.com/
# Default for facebook is {{ site/url }}
socialshare:
  de: "Portal mit Tipps für Flüchtlinge aus der Ukraine zu einem gelungenen Start in der Schweiz https://www.HelloUkraine.ch #StandWithUkraine"
  uk: "Портал з порадами для біженців з України про успішний старт у Швейцарії https://www.HelloUkraine.ch #StandWithUkraine"
  ru: "Портал с советами для беженцев из Украины об успешном старте в Швейцарии https://www.HelloUkraine.ch #StandWithUkraine"
  en: "Portal with tips for refugees from Ukraine on a successful start in Switzerland https://www.HelloUkraine.ch #StandWithUkraine"



plugins:
  - jemoji
  - jekyll-spaceship
  



defaults:
  - scope:
      path: ""
    values:
      layout: "default"


