theme: jekyll-theme-cayman
domain: www.helloukraine.ch      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: http://www.helloukraine.ch
baseurl: /

title: Hello Ukraine
description: "..."

revolut: https://www.revolut.com/referral/pascal30y!MAR1-22-AR
contactform: https://forms.zohopublic.eu/helloukrainech/form/Contact/formperma/0BLf1QF03ZRSGTgvQgJfUay_IhGAagmouP6iTl387Vo

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jemoji
  - jekyll-spaceship
  
